Created by Olivia Williams, FFHS 19

# Teil 4 der Semesterarbeit: Page-Rank

Es wird empfohlen das mitgegebene Dokument als zusätzliche Erklärung zu verwenden, das teilsweise Stellen besser erklärt werden als nur das Jupyter Notebook alleine. 

Import der Library numpy, um mit Matrizen rechnen zu können.

In [1]:
import numpy as np

# Erster Fall mit angepasster Adjazenzmatrix: Anpassung der Adjazenzmatrix

Als erstes soll die Matrix aufgebaut werden. In diesem Fall entspricht dies einer 7x7 Matrix. Die Einträge können aus dem mitgegebenen Dokument gelesen werden.

In [2]:
# Aufbau der Adjazenzmatrix mit insgesamt 49 Einträgen
adjm = np.zeros((7,7))

# erste Spalte
adjm[0][0]= 0
adjm[0][1]= 1/3
adjm[0][2]= 0
adjm[0][3]= 0
adjm[0][4]= 0
adjm[0][5]= 1/3
adjm[0][6]= 0
# zweite Spalte
adjm[1][0]= 0.5
adjm[1][1]= 0
adjm[1][2]= 0
adjm[1][3]= 0
adjm[1][4]= 0
adjm[1][5]= 1/3
adjm[1][6]= 0
# dritte Spalte
adjm[2][0]= 0
adjm[2][1]= 1/3
adjm[2][2]= 0
adjm[2][3]= 0
adjm[2][4]= 1
adjm[2][5]= 0
adjm[2][6]= 0
# vierte Spalte
adjm[3][0]= 0
adjm[3][1]= 0
adjm[3][2]= 1
adjm[3][3]= 0
adjm[3][4]= 0
adjm[3][5]= 0
adjm[3][6]= 0
# fünfte Spalte
adjm[4][0]= 0
adjm[4][1]= 0
adjm[4][2]= 0
adjm[4][3]= 1
adjm[4][4]= 0
adjm[4][5]= 0
adjm[4][6]= 0
# sechste Spalte
adjm[5][0]= 0.5
adjm[5][1]= 1/3
adjm[5][2]= 0
adjm[5][3]= 0
adjm[5][4]= 0
adjm[5][5]= 0
adjm[5][6]= 0
# siebte Spalte
adjm[6][0]= 0
adjm[6][1]= 0
adjm[6][2]= 0
adjm[6][3]= 0
adjm[6][4]= 0
adjm[6][5]= 1/3
adjm[6][6]= 0
print(adjm)

[[0.         0.33333333 0.         0.         0.         0.33333333
  0.        ]
 [0.5        0.         0.         0.         0.         0.33333333
  0.        ]
 [0.         0.33333333 0.         0.         1.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.5        0.33333333 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.        ]]


Nun soll diese Matrix in eine Google Matrix überführt werden. Dies entspricht der Matrix M, die auf Seite 5 des mitgegebenen Dokuments gelesen werden kann. Um dies berechnen zu können, wird der Term in zwei Teile aufegtrennt und anschliessend wieder zusammengeführt. Somit wird zuerst der Term links von dem Pluszeichen berechnet. Dieser Teil entspricht der Berücksichtigung der eingebauten "dangling page". Also das erste dyadische Produkt entsteht aus dem Einheitsvektor und dem Vektor a. Wie dieser Vektor festgelegt werden kann, wird in dem mitgegebenen Dokument erklärt.

In [3]:
# Berechnung der Google Matrix
# Gemäss Seite 5 soll die Google Matrix berechnet werden
# 1) Der Dämpfungsfaktor beta soll 0.8 betragen
# 2) A entspricht der Adjazenzmatrix
# 3) 1/n entspricht hier 1/7
# 4) e entspricht hier dem Einheitsvektor [1,1,1,1,1,1,1]
# 5) a entspricht hier [0,0,0,0,0,0,1], da nur in der letzten Zeile ein dangling page vorkommt
# 6) (1 - beta) soll hier 0.2 betragen

# Die erste Berechung der "dangling pages"
# Als erster das dyadische Produkt von 4) und 5)
e1 = np.array([1,1,1,1,1,1,1]) 
a1 = np.array([0,0,0,0,0,0,1])
dyadisches_produkt1= np.outer(e1,a1)
print(dyadisches_produkt1)

[[0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]]


Das erreichte dyadische Produkt wird nun mit dem Wert (1/7) multipliziert und in eine weitere Variable festgehalten.

In [4]:
# Als zweites die Multiplikation des dyadischen Produkts mit dem Wert aus 3)
dyadisches_produkt_mult =(1/7)*dyadisches_produkt1
print(dyadisches_produkt_mult)

[[0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.
  0.14285714]]


Die Adjazenzmatrix und dyadisches_produkt_mult werden summiert.

In [5]:
# Als drittes soll die Adjazenzmatrix und die vorhin berechnete Matrix summiert werden
# Der Betrag in der ersten Klammer aus der Gleichung ist so bestimmt
matrix = adjm+dyadisches_produkt_mult
print(matrix)

[[0.         0.33333333 0.         0.         0.         0.33333333
  0.14285714]
 [0.5        0.         0.         0.         0.         0.33333333
  0.14285714]
 [0.         0.33333333 0.         0.         1.         0.
  0.14285714]
 [0.         0.         1.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         1.         0.         0.
  0.14285714]
 [0.5        0.33333333 0.         0.         0.         0.
  0.14285714]
 [0.         0.         0.         0.         0.         0.33333333
  0.14285714]]


Nun soll der Term rechts von dem Pluszeichen berechnet werden. Das zweite dyadische Produkt aus den Einheitsvektoren e2 und a2 soll gebildet werden.

In [6]:
# Als viertes soll das zweite dyadische Produkt aus dem zweiten Teil der Gleichung berechnet werden
# Es handelt sich hierbei um die Teillösung für die "spider traps"
e2 = np.array([1,1,1,1,1,1,1]) 
a2 = np.array([1,1,1,1,1,1,1])
dyadisches_produkt2= np.outer(e2,a2)
print(dyadisches_produkt2)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


Die berechneten Teile sollen un in eine Google Matrix zusammengeführt werden. 

In [7]:
# Hier sollen die berechneten Teile als Google Matrix zusammengeführt werden
# Dies entspricht der roten Gleichung auf der Seite 5
Google_Matrix = 0.8*matrix + 0.2*(1/7)*dyadisches_produkt2
print(Google_Matrix)

[[0.02857143 0.2952381  0.02857143 0.02857143 0.02857143 0.2952381
  0.14285714]
 [0.42857143 0.02857143 0.02857143 0.02857143 0.02857143 0.2952381
  0.14285714]
 [0.02857143 0.2952381  0.02857143 0.02857143 0.82857143 0.02857143
  0.14285714]
 [0.02857143 0.02857143 0.82857143 0.02857143 0.02857143 0.02857143
  0.14285714]
 [0.02857143 0.02857143 0.02857143 0.82857143 0.02857143 0.02857143
  0.14285714]
 [0.42857143 0.2952381  0.02857143 0.02857143 0.02857143 0.02857143
  0.14285714]
 [0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.2952381
  0.14285714]]


Die Google Matrix soll nun auf vier Nachkommastellen gerundet werden.

In [8]:
# Die Google_Matrix soll auf vier Nachkommastellen gerundet werden
# Erste Zeile
Google_Matrix[2][2]=round(Google_Matrix[2][2],4)
Google_Matrix[2][3]=round(Google_Matrix[2][3],4)
Google_Matrix[2][4]=round(Google_Matrix[2][4],4)
Google_Matrix[2][5]=round(Google_Matrix[2][5],4)
Google_Matrix[2][6]=round(Google_Matrix[2][6],4)
# Vierte Zeile
Google_Matrix[3][0]=round(Google_Matrix[3][0],4)
Google_Matrix[3][1]=round(Google_Matrix[3][1],4)
Google_Matrix[3][2]=round(Google_Matrix[3][2],4)
Google_Matrix[3][3]=round(Google_Matrix[3][3],4)
Google_Matrix[3][4]=round(Google_Matrix[3][4],4)
Google_Matrix[3][5]=round(Google_Matrix[3][5],4)
Google_Matrix[3][6]=round(Google_Matrix[3][6],4)
# Fünfte Zeile
Google_Matrix[4][0]=round(Google_Matrix[4][0],4)
Google_Matrix[4][1]=round(Google_Matrix[4][1],4)
Google_Matrix[4][2]=round(Google_Matrix[4][2],4)
Google_Matrix[4][3]=round(Google_Matrix[4][3],4)
Google_Matrix[4][4]=round(Google_Matrix[4][4],4)
Google_Matrix[4][5]=round(Google_Matrix[4][5],4)
Google_Matrix[4][6]=round(Google_Matrix[4][6],4)
# Sechste Zeile
Google_Matrix[5][0]=round(Google_Matrix[5][0],4)
Google_Matrix[5][1]=round(Google_Matrix[5][1],4)
Google_Matrix[5][2]=round(Google_Matrix[5][2],4)
Google_Matrix[5][3]=round(Google_Matrix[5][3],4)
Google_Matrix[5][4]=round(Google_Matrix[5][4],4)
Google_Matrix[5][5]=round(Google_Matrix[5][5],4)
Google_Matrix[5][6]=round(Google_Matrix[5][6],4)
# Siebte Zeile
Google_Matrix[6][0]=round(Google_Matrix[6][0],4)
Google_Matrix[6][1]=round(Google_Matrix[6][1],4)
Google_Matrix[6][2]=round(Google_Matrix[6][2],4)
Google_Matrix[6][3]=round(Google_Matrix[6][3],4)
Google_Matrix[6][4]=round(Google_Matrix[6][4],4)
Google_Matrix[6][5]=round(Google_Matrix[6][5],4)
Google_Matrix[6][6]=round(Google_Matrix[6][6],4)
print(Google_Matrix)

[[0.02857143 0.2952381  0.02857143 0.02857143 0.02857143 0.2952381
  0.14285714]
 [0.42857143 0.02857143 0.02857143 0.02857143 0.02857143 0.2952381
  0.14285714]
 [0.02857143 0.2952381  0.0286     0.0286     0.8286     0.0286
  0.1429    ]
 [0.0286     0.0286     0.8286     0.0286     0.0286     0.0286
  0.1429    ]
 [0.0286     0.0286     0.0286     0.8286     0.0286     0.0286
  0.1429    ]
 [0.4286     0.2952     0.0286     0.0286     0.0286     0.0286
  0.1429    ]
 [0.0286     0.0286     0.0286     0.0286     0.0286     0.2952
  0.1429    ]]


# Erster Fall mit angepasster Adjazenzmatrix: Berechnung eines stationären Vektors

Nun soll die berechnete Google Matrix auf Konvergenz untersucht werden. Dies bedeutet, das in einer Schleife ein Zustandvektor berechnet wird. Anschliessend innerhalb desselben Schleifendurchgangs wird der nächste Zustandsvektor berechnet, der erreicht wird, wenn die nächste Potenz angwendet wird: (A^n)*B und A^(n+1)*B.
Nun können diese beiden Vektoren verglichen werden. Sollten diese mit drei Nachkommastellen übereinstimmen, so ist die Konvergenz erreicht.

Dazu soll ein Vektor B eingeführt werden, der dem Zustandvektor entspricht.

In [9]:
# Hier soll nun anhand der Potenzierung der Google Matrix und eine Multiplikation mit dem Zustandsvektor
# eine Konvergenz erreicht werden. Anhand einer einfachen Schleife wird das nächste Ergebnis mit dem vorangegangenen Ergebnis
# verglichen. Sollten diese Ergebnisse gleich sein, ist die Konvergenz erreicht.

# Vektor B, die dem Zustandsvektor entspricht, angefangen mit den Werten 1/7
B = np.array([[1/7],[1/7],[1/7],[1/7],[1/7],[1/7],[1/7]])  

Als nächstes soll in die Variable A die Google Matrix kopiert werden.

In [10]:
# Matrix A entspricht dem "Container", angefangen mit den Google Matrix Werten
# Diese Matrix wird iterativ mit den Google Matrix Werten multipliziert und am Ende mit dem Zustandsvektor ebenfalls multipliziert
# Dieser errechnete Wert wird mit dem vorangegangenen Wert verglichen. Sind sich diese nahe genug (drei Nachkommastellen), so handelt es sich
# um eine Konvergenz
A = Google_Matrix.copy()

In einem nächsten Schritt wird die Schleife betreten, die bis zum Wert 20 iteriert wird. Zuerst werden die Matrizen miteinander multipliziert und anschliessend mit B. In einem dritten Schritt wird dies für den nächsten Zustandsvektor wiederholt. Die Werte werden anschliessend gerundet.

Mit einer einfachen if Anweisung sollen nun die errechneten Zustandsvektoren verglichen werden. Gibt es eine Übereinstimmung, so ist die Konvergenz gefunden.

In [11]:
i=0
while i <= 20:
    # Erster Schritt, Multiplikation der Matrizen
    A=np.dot(A,Google_Matrix)
    # Zweiter Schritt, Multiplikation mit dem Zustandsvektor 
    nZ=np.dot(A,B)
    
    # Dritter Schritt, nächste Potenz
    A=np.dot(A,Google_Matrix)
    # Vierter Schitt, nächster Zustandsvektor bestimmen
    nZ2=np.dot(A,B)
    
    # Fünfter Schritt, Vektoren vergleichen
    # Sollten diese mit drei Nachkommastellen übereinstimmten, ist die Konvergenz erreicht
    # Zuerst sollen die Werte gerundet werden
    # nZ gerundet
    nZ[0]=np.round(nZ[0],3)
    nZ[1]=np.round(nZ[1],3)
    nZ[2]=np.round(nZ[2],3)
    nZ[3]=np.round(nZ[3],3)
    nZ[4]=np.round(nZ[4],3)
    nZ[5]=np.round(nZ[5],3)
    nZ[6]=np.round(nZ[6],3)
    # nZ2 gerundet
    nZ2[0]=np.round(nZ2[0],3)
    nZ2[1]=np.round(nZ2[1],3)
    nZ2[2]=np.round(nZ2[2],3)
    nZ2[3]=np.round(nZ2[3],3)
    nZ2[4]=np.round(nZ2[4],3)
    nZ2[5]=np.round(nZ2[5],3)
    nZ2[6]=np.round(nZ2[6],3)
    
    if nZ[0]==nZ2[0] and nZ[1]==nZ2[1] and nZ[2]==nZ2[2] and nZ[3]==nZ2[3] and nZ[4]==nZ2[4] and nZ[5]==nZ2[5] and nZ[6]==nZ2[6]:
        print("Eine annehmbare Konvergenz ist bei "+ str(i) + " erreicht")
        k1 = (i*2)+2
        k2 = k1+1
        print("Dies entspricht einem Vergleich zwischen den Klicks " + str(k1) + " und " + str(k2))
        print("Der anzunehmbare sationäre Vektor lautet dazu: ")
        print("")
        print(nZ)
        print("")
        break;  
    else:
        print("Noch keine Konvergenz bei " + str(i) + " erreicht")
        print("")
    i  += 1

Noch keine Konvergenz bei 0 erreicht

Noch keine Konvergenz bei 1 erreicht

Noch keine Konvergenz bei 2 erreicht

Noch keine Konvergenz bei 3 erreicht

Noch keine Konvergenz bei 4 erreicht

Noch keine Konvergenz bei 5 erreicht

Noch keine Konvergenz bei 6 erreicht

Noch keine Konvergenz bei 7 erreicht

Noch keine Konvergenz bei 8 erreicht

Eine annehmbare Konvergenz ist bei 9 erreicht
Dies entspricht einem Vergleich zwischen den Klicks 20 und 21
Der anzunehmbare sationäre Vektor lautet dazu: 

[[0.087]
 [0.096]
 [0.231]
 [0.22 ]
 [0.212]
 [0.096]
 [0.061]]



# Zweiter Fall mit unangepasster Adjazenzmatrix: Berechnung der Zustandsvektoren

Nun sollen die Zustandsvektoren in dem gleichen Schleifendurchgang ausgegeben werden. Nur in diesem Fall wird nicht mit der Google Matrix gerechnet, sondern mit der Ausgangmatrix adjm, die ganz am Anfang bestimmt wurde. In die Variable A wird adjm kopiert und der Vektor B wird erneut erwähnt. Der Schleifendurchgang wird nun bis 9 berücksichtig, dieser Wert entspricht dem erreichten Wert aus dem ersten Schleifendurchgang. Es wird ebenfalls der erste und nachfolgende Zustandsvektor berechnet, gerundet und dieses Mal direkt ausgegeben, also wird kein Vergleich angestellt.

In [12]:
# Mit der unbehandelten Adjanzenmatrix soll nun auch in einer Schleife gesehen werden, wie sich der Zustandsvektor bis i, in diesem
# Falle 9, verändert und ob sich daraus tatsächlich eine rasche Konvergenz gegen null entwickelt.
print("In einer gleichen Schleife wie oben sollen nun die Zustandsvektoren der unbehandelten Adjanzenzmatrix adjm berechnet werden.")
print("Die berechneten Zustandsvektoren bis j= " +str(i)+ " sollen hier ausgegeben werden. Deren Entwicklung ist Gegenstand der Untersuchung:")

# Eine Kopie der Matrix adjm, der unbehandelten Matrix in die Variable A
A = adjm.copy()

# Vektor B, die dem vorangegangenen Zustandsvektor entspricht, angefangen mit den Werten 1/7
B = np.array([[1/7],[1/7],[1/7],[1/7],[1/7],[1/7],[1/7]]) 

j=0
while j <= i:
    # Erster Schritt, Multiplikation der Matrizen, dieses mal nicht die Google Matrix, sondern die Matrix adjm 
    A=np.dot(A,adjm)
    # Zweiter Schritt, Multiplikation mit dem Zustandsvektor 
    nZ=np.dot(A,B)
    
    # Dritter Schritt, nächste Potenz
    A=np.dot(A,adjm)
    # Vierter Schitt, nächster Zustandsvektor bestimmen
    nZ2=np.dot(A,B)
    
    # Die Werte sollen mit drei Nachkommastellen gerundet werden
    nZ[0]=np.round(nZ[0],3)
    nZ[1]=np.round(nZ[1],3)
    nZ[2]=np.round(nZ[2],3)
    nZ[3]=np.round(nZ[3],3)
    nZ[4]=np.round(nZ[4],3)
    nZ[5]=np.round(nZ[5],3)
    nZ[6]=np.round(nZ[6],3)
    # nZ2 gerundet
    nZ2[0]=np.round(nZ2[0],3)
    nZ2[1]=np.round(nZ2[1],3)
    nZ2[2]=np.round(nZ2[2],3)
    nZ2[3]=np.round(nZ2[3],3)
    nZ2[4]=np.round(nZ2[4],3)
    nZ2[5]=np.round(nZ2[5],3)
    nZ2[6]=np.round(nZ2[6],3)
    
    # Nun sollen alle Zustandsvektoren ausgegeben werden
    print("")
    print("A potenziert mit " + str((j*2)+2) + " multipliziert mit 1/7 (Vektor B) ergibt: ")
    print("")
    print(nZ)
    print("")
    print("A potenziert mit " + str((j*2)+2+1) + " multipliziert mit 1/7 (Vektor B) ergibt: ")
    print("")
    print(nZ2)
    print("")
    j  += 1

In einer gleichen Schleife wie oben sollen nun die Zustandsvektoren der unbehandelten Adjanzenzmatrix adjm berechnet werden.
Die berechneten Zustandsvektoren bis j= 9 sollen hier ausgegeben werden. Deren Entwicklung ist Gegenstand der Untersuchung:

A potenziert mit 2 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.079]
 [0.087]
 [0.183]
 [0.19 ]
 [0.143]
 [0.087]
 [0.04 ]]

A potenziert mit 3 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.058]
 [0.069]
 [0.172]
 [0.183]
 [0.19 ]
 [0.069]
 [0.029]]


A potenziert mit 4 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.046]
 [0.052]
 [0.213]
 [0.172]
 [0.183]
 [0.052]
 [0.023]]

A potenziert mit 5 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.035]
 [0.04 ]
 [0.2  ]
 [0.213]
 [0.172]
 [0.04 ]
 [0.017]]


A potenziert mit 6 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.027]
 [0.031]
 [0.185]
 [0.2  ]
 [0.213]
 [0.031]
 [0.013]]

A potenziert mit 7 multipliziert mit 1/7 (Vektor B) ergibt: 

[[0.021]
 [0.024]
 [0.224]
 [0.185]
 [0.2  ]
 [0.02

Die Interpretation der Resultate kann im Dokument unter "Interpretation des Resultats" nachvollzogen werden.

# Zweiter Fall mit unangepasster Adjazenzmatrix: Zusätzliche Untersuchung der Konvergenz

Es soll hier nun gesehen werden, ob eine Konvergenz mit der unangepassten Adjazenzmatrix erreicht werden kann. Gemäss der Erklärung des Dokuments sollte dies nicht der Fall sein, für mehr siehe bitte das Dokument. Dazu wird die erste Schleife erneut angewendet, nur in diesem Falle wird nicht die Google Matrix als Grundlage der Berechnungen verwendet, sondern die Ausgangsmatrix adjm, die jedoch in dieselbe Matrix gegeben wird.

In [13]:
B = np.array([[1/7],[1/7],[1/7],[1/7],[1/7],[1/7],[1/7]])
Google_Matrix = adjm
A = Google_Matrix.copy()

i=0
while i <= 20:
    # Erster Schritt, Multiplikation der Matrizen
    A=np.dot(A,Google_Matrix)
    # Zweiter Schritt, Multiplikation mit dem Zustandsvektor 
    nZ=np.dot(A,B)
    
    # Dritter Schritt, nächste Potenz
    A=np.dot(A,Google_Matrix)
    # Vierter Schitt, nächster Zustandsvektor bestimmen
    nZ2=np.dot(A,B)
    
    # Fünfter Schritt, Vektoren vergleichen
    # Sollten diese mit drei Nachkommastellen übereinstimmten, ist die Konvergenz erreicht
    # Zuerst sollen die Werte gerundet werden
    # nZ gerundet
    nZ[0]=np.round(nZ[0],3)
    nZ[1]=np.round(nZ[1],3)
    nZ[2]=np.round(nZ[2],3)
    nZ[3]=np.round(nZ[3],3)
    nZ[4]=np.round(nZ[4],3)
    nZ[5]=np.round(nZ[5],3)
    nZ[6]=np.round(nZ[6],3)
    # nZ2 gerundet
    nZ2[0]=np.round(nZ2[0],3)
    nZ2[1]=np.round(nZ2[1],3)
    nZ2[2]=np.round(nZ2[2],3)
    nZ2[3]=np.round(nZ2[3],3)
    nZ2[4]=np.round(nZ2[4],3)
    nZ2[5]=np.round(nZ2[5],3)
    nZ2[6]=np.round(nZ2[6],3)
    
    if nZ[0]==nZ2[0] and nZ[1]==nZ2[1] and nZ[2]==nZ2[2] and nZ[3]==nZ2[3] and nZ[4]==nZ2[4] and nZ[5]==nZ2[5] and nZ[6]==nZ2[6]:
        print("Eine annehmbare Konvergenz ist bei "+ str(i) + " erreicht")
        k1 = (i*2)+2
        k2 = k1+1
        print("Dies entspricht einem Vergleich zwischen den Klicks " + str(k1) + " und " + str(k2))
        print("Der anzunehmbare sationäre Vektor lautet dazu: ")
        print("")
        print(nZ)
        print("")
        break;  
    else:
        print("Noch keine Konvergenz bei " + str(i) + " erreicht")
        print("")
    i  += 1

Noch keine Konvergenz bei 0 erreicht

Noch keine Konvergenz bei 1 erreicht

Noch keine Konvergenz bei 2 erreicht

Noch keine Konvergenz bei 3 erreicht

Noch keine Konvergenz bei 4 erreicht

Noch keine Konvergenz bei 5 erreicht

Noch keine Konvergenz bei 6 erreicht

Noch keine Konvergenz bei 7 erreicht

Noch keine Konvergenz bei 8 erreicht

Noch keine Konvergenz bei 9 erreicht

Noch keine Konvergenz bei 10 erreicht

Noch keine Konvergenz bei 11 erreicht

Noch keine Konvergenz bei 12 erreicht

Noch keine Konvergenz bei 13 erreicht

Noch keine Konvergenz bei 14 erreicht

Noch keine Konvergenz bei 15 erreicht

Noch keine Konvergenz bei 16 erreicht

Noch keine Konvergenz bei 17 erreicht

Noch keine Konvergenz bei 18 erreicht

Noch keine Konvergenz bei 19 erreicht

Noch keine Konvergenz bei 20 erreicht



Die Konvergenz wird nicht erreicht.